### ISSUE TITLE
beam-migrate fails to build on ghc 8.6.3

### ISSUE THREAD

**Issue by ericnething** [tathougies/beam#344]
This is happens with [this commit](https://github.com/tathougies/beam/commit/c1b2aacd7c6a6d2e2679763acb4931591e7f4d6c) on master.

`beam-migrate` fails with this error:

~~~
Database/Beam/Migrate/Generics/Types.hs:23:10: error:
    • Illegal nested constraint ‘CheckedDatabaseEntityDefaultRequirements
                                   be x syntax’
      (Use UndecidableInstances to permit this)
    • In the instance declaration for
        ‘GAutoMigratableDb syntax (S1 f (Rec0 (CheckedDatabaseEntity be db x)))’
   |
23 | instance ( Selector f, IsCheckedDatabaseEntity be x
   |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...
cabal: Failed to build beam-migrate-0.3.2.1
~~~

Strangely, if I build `beam-migrate` alone, it works. But if I build it as part of my project, it fails.

`beam-core-0.7.2.2` won't compile either because of an upper constraint on `vector-sized` that is too low, but that has been fixed in 0.7.2.3 which has not been released yet on hackage.

**Comment by tathougies** [comment]
Yeah, sorry been a bit disorganized with releases recently.

Does the compile work if you enable `UndecidableInstances`?

**Comment by tathougies** [comment]
I just built master with stack lts-13.0 (GHC-8.6.3) on OS X and it compiled. Can you confirm?

**Comment by tathougies** [comment]
duplicate of #315
