### ISSUE TITLE
Compiling with GHC 8.2.2

### ISSUE THREAD

**Issue by boj** [tathougies/beam#163]
Given the following:

```haskell
data ManagedAuthT f
  = ManagedAuth
  { _matCustomer      :: PrimaryKey CustomerT f
  , _matAllowBusiness :: Columnar f Bool
  } deriving (Generic)
makeLenses ''ManagedAuthT
instance Beamable ManagedAuthT
type ManagedAuth = ManagedAuthT Identity
deriving instance Show ManagedAuth
deriving instance Eq ManagedAuth
deriving instance Ord ManagedAuth
instance Table ManagedAuthT where
  data PrimaryKey ManagedAuthT f =
    ManagedAuthKey (PrimaryKey CustomerT f) deriving (Generic)
  primaryKey = ManagedAuthKey <$> _matCustomer
instance Beamable (PrimaryKey ManagedAuthT)
type ManagedAuthKey = PrimaryKey ManagedAuthT Identity
deriving instance Show ManagedAuthKey
deriving instance Eq ManagedAuthKey
deriving instance Ord ManagedAuthKey

ManagedAuth (CustomerKey (LensFor matCustomerId)) _ = tableLenses
```

I get this error:

```haskell
src/Database.hs:482:35: error:
    • Cannot instantiate unification variable ‘p14’
      with a type involving foralls:
        microlens-0.4.8.1:Lens.Micro.Type.Lens'
          (ManagedAuthT f11) (Columnar f11 (Auto CustomerId))
        GHC doesn't yet support impredicative polymorphism
    • In the pattern: LensFor matCustomerId
      In the pattern: CustomerKey (LensFor matCustomerId)
      In the pattern: ManagedAuth (CustomerKey (LensFor matCustomerId)) _
    |
482 | ManagedAuth (CustomerKey (LensFor matCustomerId)) _ = tableLenses
    | 
```

1. Is there a way to use `Control.Lens` to derive the Id fields?
2. What do I need to consider to make this build with GHC 8.2.2?

**Comment by tathougies** [comment]
You can use `Control.Lens` the normal way to make lenses for beam types. They are -- after all -- regular Haskell data types. As it stands, that is my current recommendation if you want lenses.

This bug is a duplicate of #114

**Comment by boj** [comment]
@tathougies Could you provide an example of how to derive `matCustomerId` correctly with `Control.Lens` (which I am using via `makeLenses`)? That is the part I feel like I am stumped on, making a lens to the id instead of the foreign association.
