### ISSUE TITLE
beam-core 0.7.2.2 build error (vector-sized)

### ISSUE THREAD

**Issue by Kleidukos** [tathougies/beam#349]
I'm getting this error when building beam-core on Stackage LTS 13.6

```haskell

--  While building package vector-sized-1.0.4.0 using:
      /home/hecate/.stack/setup-exe-cache/x86_64-linux-tinfo6/Cabal-simple_mPHDZzAJ_2.4.0.1_ghc-8.6.3 --builddir=.stack-work/dist/x86_64-linux-tinfo6/Cabal-2.4.0.1 build --ghc-options " -ddump-hi -ddump-to-file -fdiagnostics-color=always"
    Process exited with code: ExitFailure 1
    Logs have been written to: /home/hecate/dev/BP/buttplug-hs/.stack-work/logs/vector-sized-1.0.4.0.log

    Configuring vector-sized-1.0.4.0...
    Preprocessing library for vector-sized-1.0.4.0..
    Building library for vector-sized-1.0.4.0..
    [1 of 8] Compiling Data.Vector.Generic.Mutable.Sized.Internal ( src/Data/Vector/Generic/Mutable/Sized/Internal.hs, .stack-work/dist/x86_64-linux-tinfo6/Cabal-2.4.0.1/build/Data/Vector/Generic/Mutable/Sized/Internal.o )
    [2 of 8] Compiling Data.Vector.Generic.Mutable.Sized ( src/Data/Vector/Generic/Mutable/Sized.hs, .stack-work/dist/x86_64-linux-tinfo6/Cabal-2.4.0.1/build/Data/Vector/Generic/Mutable/Sized.o )
    [3 of 8] Compiling Data.Vector.Generic.Sized.Internal ( src/Data/Vector/Generic/Sized/Internal.hs, .stack-work/dist/x86_64-linux-tinfo6/Cabal-2.4.0.1/build/Data/Vector/Generic/Sized/Internal.o )
    [4 of 8] Compiling Data.Vector.Generic.Sized ( src/Data/Vector/Generic/Sized.hs, .stack-work/dist/x86_64-linux-tinfo6/Cabal-2.4.0.1/build/Data/Vector/Generic/Sized.o )

    /tmp/stack22159/vector-sized-1.0.4.0/src/Data/Vector/Generic/Sized.hs:975:63: error:
        • Expected kind ‘* -> Nat -> Nat’, but ‘n’ has kind ‘Nat’
        • In the second argument of ‘Vector’, namely ‘(n * m)’
          In the type signature:
            concatMap :: (VG.Vector v a, VG.Vector v b) =>
                         (a -> Vector v m b) -> Vector v n a -> Vector v (n * m) b
        |
    975 |           => (a -> Vector v m b) -> Vector v n a -> Vector v (n*m) b
        |                                                               ^^^

```

My intuition is that `beam-core`'s hard dep on `vector-sized > 1.1` is the reason   
Currently, `vector-sized` is at version 1.2 on Hackage.  
Would it be possible to update this dependency?

my `extra-deps` looks like

```yaml
- beam-core-0.7.2.2@sha256:4eb3e12584c01d2218845581322c7632295d9e76c565c25d4010549d55d16dbb
- beam-migrate-0.3.2.1@sha256:fb9d918e43f296c507cf94823aed4bc2790e4b7a0c407eaa027118d980350fbe
- beam-sqlite-0.3.2.3@sha256:5b3a3a81f06ad05d2d461847b3c1bb4130a1dd38c8b5dc129df311c4230fd46b
- containers-0.5.11.0@sha256:28ad7337057442f75bc689315ab4ec7bdf5e6b2c39668f306672cecd82c02798
- unagi-chan-0.4.1.0@sha256:97e08dd9a73462ca284bfd2f904cd471c94e1207c2dd79a59efcc8fe2c93de41
- vector-sized-1.0.4.0@sha256:d5cdea82b87ff7a5158d784e6869866e6a2c258f0a035279e0168b55350a723f
```

**Comment by CaptJakk** [comment]
I too had this exact error just now. Trying to build on 13.1 with a handful of extra-deps.

**Comment by CaptJakk** [comment]
I ended up getting up and running doing the following in my stack.yaml

```yaml
  - git: git@github.com:tathougies/beam.git
    commit: 950efcb270f689f622c861ac0a3e9fc2422910ee
    subdirs:
      - beam-core
      - beam-postgres
      - beam-migrate
```

**Comment by Kleidukos** [comment]
@CaptJakk Were you able to use `beam-migrate` with that setup? I'm doing `stack install beam-migrate` in my stack project (not the global project) and it's not present in my bin path…

**Comment by CaptJakk** [comment]
I have been unable to get `stack install beam-migrate` to deposit to my bin path at all. That said, I suspect this is not an issue with beam so much as it is with stack. Not sure though
